apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.name }}-pdb
  namespace: {{ .Release.Namespace }}
spec:
  maxUnavailable: 50%
  selector:
    matchLabels:
      app: {{ .Values.name }}
