stages:
  - test
  - build

testShort:
  stage: test
  image: golang:1.15
  script:
    - go test ./...internal/... --short -v

# TODO(donfrigo): reuse docker-compose and the db/Dockerfile if possible
test:
  stage: test
  image: golang:1.15
  services:
    - name: timescale/timescaledb:1.7.4-pg12
      alias: timescale
  variables:
    POSTGRES_DB: midgard
    POSTGRES_USER: midgard
    POSTGRES_PASSWORD: password
    POSTGRES_HOST_AUTH_METHOD: trust
    DB_HOST: timescale
    DB_PORT: "5432"
  script:
    # Install psql to populate database
    - apt-get update && apt-get install -y postgresql-client
    - PGPASSWORD=password psql -h timescale -p 5432 -d midgard -U midgard midgard < ./db/ddl.sql
    - go test -run 'E2E' -v -p 1 ./...internal/...

