variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - lint
  - test
  - smoke
  - build

lint:
  stage: lint
  image: golangci/golangci-lint:v1.32
  script:
    - golangci-lint run -v

test:
  stage: test
  image: docker/compose:1.27.4
  services:
    - docker:19.03.13-dind
  variables:
    DB_HOST: docker
    DB_PORT: "5433"
  script:
    - docker-compose up -d pgtest
    - apk add --no-cache git make musl-dev go
    - go test -v -p 1 ./...

smoke:
  stage: smoke
  image: docker/compose:1.27.4
  services:
    - docker:19.03.13-dind
  artifacts:
    when: on_failure
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./logs/
  except:
    - schedules
  before_script:
    - apk update
    - apk add make git jq curl
    - docker build -t registry.gitlab.com/thorchain/midgard:develop .
    - git clone --single-branch -b $CI_COMMIT_BRANCH https://gitlab.com/thorchain/thornode.git || git clone --single-branch -b develop https://gitlab.com/thorchain/thornode.git
    - cd thornode
    - test master = $(git rev-parse --abbrev-ref HEAD) && docker pull registry.gitlab.com/thorchain/thornode:mocknet
    - make -C build/docker reset-mocknet-standalone
  script:
    - git clone --single-branch -b $CI_COMMIT_BRANCH https://gitlab.com/thorchain/heimdall.git || git clone --single-branch -b develop https://gitlab.com/thorchain/heimdall.git
    - cd ./heimdall
    - make build smoke
  after_script:
    - ./thornode/scripts/docker_logs.sh

build:
  stage: build
  image: docker:stable
  services:
    - docker:19.03.13-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --tag $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
