stages:
  - lint
  - test
  - build

lint:
  stage: lint
  image: golangci/golangci-lint:v1.32
  script:
    - golangci-lint run -v

test:
  stage: test
  image: docker/compose:1.27.4
  services:
    - docker:19.03.13-dind
  variables:
    DB_HOST: docker
    DB_PORT: "5433"
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker-compose up -d pgtest
    - apk add --no-cache git make musl-dev go
    - go test -v -p 1 ./...

