version: '3'

services:
  midgard:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        thornode_host: thormock:8081
        pg_host: pg
    image: midgard
    ports:
      - 8080:8080
    links:
      - pg
    depends_on:
      - pg
  pg:
    build:
      context: ./db/
    ports:
      - 5432:5432
  pgtest:
    build:
      context: ./db/
    ports:
      - 5433:5432
