version: '3'

services:
  midgard:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        thornode_host: thormock:8081
        pg_host: pg
    image: midgard
    ports:
      - 8080:8080
    links:
      - pg
    depends_on:
      - pg

  pg:
    image: timescale/timescaledb:2.2.0-pg13
    shm_size: 512m
    command: postgres -c plan_cache_mode=force_custom_plan
    environment:
      - POSTGRES_DB=midgard
      - POSTGRES_USER=midgard
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  pg2:
    image: timescale/timescaledb:2.2.0-pg13
    shm_size: 512m
    command: postgres -c plan_cache_mode=force_custom_plan
    environment:
      - POSTGRES_DB=midgard
      - POSTGRES_USER=midgard
      - POSTGRES_PASSWORD=password
    ports:
      - 6432:5432

  pgtest:
    image: timescale/timescaledb:2.2.0-pg13
    command: postgres -c plan_cache_mode=force_custom_plan
    environment:
      - POSTGRES_DB=midgard
      - POSTGRES_USER=midgard
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5432
