openapi: 3.0.0
info:
    title: Midgard Public API
    version: 0.6.0
    contact:
        email: devs@thorchain.org
    description: >-
        The Midgard Public API queries THORChain and any chains linked via the Bifröst
        and prepares information about the network to be readily available for public users.
        The API parses transaction event data from THORChain and stores them
        in a time-series database to make time-dependent queries easy.
        Midgard does not hold critical information.
        To interact with BEPSwap and Asgardex, users should query THORChain directly.
paths:
    /v2/doc:
        get:
            operationId: GetDocs
            summary: Get Documentation
            description: Swagger/OpenAPI 3.0 specification generated documents.
            responses:
              "200":
                description: swagger/OpenAPI 3.0 spec generated docs
            tags:
              - Documentation

    "/v1/health":
        get:
            operationId: GetHealth
            summary: Get Health
            description: Returns an object containing the health response of the API.
            responses:
              "200":
                $ref: '#/components/responses/HealthResponse'

components:
  responses:
    HealthResponse:
      description: Returns an health status of Midgard
      content:
        application/json:
          schema:
            type: object
            required:
            - database
            - scannerHeight
            - inSync
            properties:
                database:
                    type: boolean
                    description: True means healthy, connected to database.
                scannerHeight:
                    type: string
                    description: Int64, the current block count.
                inSync:
                    type: boolean
                    description: True means healthy. False means Midgard is still catching up to the chain.
