steps:
    - name: 'gcr.io/kaniko-project/executor:latest'
      args:
          - --destination=gcr.io/$_REPO_PROJECT/midgard-test/$_SERVICE_NAME:$COMMIT_SHA
          - --cache=true
          - --cache-ttl=6h
          - '-f'
          - k8s-packages/$_SERVICE_NAME/Dockerfile
timeout: 3000s
substitutions:
    _REPO_PROJECT: thorswap-devops
    _SERVICE_NAME: producer

